Solution
mate-academy/py-movie-api pull request #123
Opened 2022-12-06 17:09 UTC by davidkrivko

2022-12-08 07:46 UTC, Abnormaltype requested changes
read the checklist before pushing your solution.

2022-12-09 08:44 UTC, Serhii-Leonenko requested changes
Remove redundant db :
![image](https://user-images.githubusercontent.com/104218550/206661252-f47802c2-5110-4283-b874-c04f6bb4a284.png)

2022-12-13 09:14 UTC, Serhii-Leonenko requested changes
Db is still here, you should not only add it to  .gitignore. Delete it from your repo `git rm --cached file_to_remove`

![image](https://user-images.githubusercontent.com/104218550/207276374-32b4019f-f9e6-458c-ab50-eac42e04cb4a.png)

2022-12-14 12:13 UTC, IvanRamyk approved these changes

2026-03-01 01:58 UTC, closed without merging