solution
mate-academy/py-movie-api pull request #246
Opened 2023-05-29 11:44 UTC by MkrtychKhachatrian

2023-05-29 12:06 UTC, vasylhnatiuk reviewed
also delete pycache form commit

2023-05-29 12:06 UTC, vasylhnatiuk commented on cinema/views.py
> +        if serializer.is_valid():
use is_valid(raise_exception=True) to do all checks automatically and raise handled errors if it's needed

2023-05-29 12:12 UTC, vasylhnatiuk requested changes
do it

2023-05-30 09:02 UTC, ArsenPidhoretskyi requested changes
.idea and pycache exists inside github
Use git rm --cached

2023-05-31 10:27 UTC, ArsenPidhoretskyi approved these changes
Well done!

2026-03-19 15:29 UTC, closed without merging