movie-api
mate-academy/py-movie-api pull request #278
Opened 2023-07-13 16:23 UTC by muhactive

2023-07-13 16:52 UTC, Bohdan-Salamakha requested changes
don't work on the master branch - it's a bad practice
https://github.com/mate-academy/py-task-guideline/blob/main/README.md#:~:text=git%20checkout%20%2Db%20develop

2023-07-14 17:09 UTC, muhactive commented
when i fix bugs they don't push come here

2023-07-14 17:13 UTC, muhactive commented
they push in my personal directory, then i push my work like new work

2023-07-14 17:25 UTC, muhactive commented
when i chenges my work

2023-07-17 07:09 UTC, muhactive commented
i change my branch and push new work

2023-07-17 07:48 UTC, olena-hul requested changes

2023-07-17 07:48 UTC, olena-hul commented on .gitignore
> +*.so
Your merge requested is still from master branch - push the code to the develop branch and change the source branch to develop

2023-07-17 10:06 UTC, muhactive commented
https://github.com/mate-academy/py-movie-api/pull/279

2023-07-17 10:07 UTC, muhactive commented
this is my new work https://github.com/mate-academy/py-movie-api/pull/279

2023-07-17 10:17 UTC, Bohdan-Salamakha requested changes
to change your PR branch from master to develop:
you need to remove your repository from github
fork the task again from mate-academy repository
push your code from local machine to forked github repository
make PR from develop branch

2023-07-19 17:28 UTC, closed without merging