solution
mate-academy/py-movie-api pull request #342
Opened 2023-09-15 18:44 UTC by VladyslavKlevanskyi

2023-09-16 09:14 UTC, Bohdan-Salamakha requested changes

2023-09-16 09:14 UTC, Bohdan-Salamakha commented on cinema/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
use is_valid(raise_exception=True) to do all checks automatically and raise handled errors if it's needed

2023-09-16 09:14 UTC, Bohdan-Salamakha commented on cinema/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
use is_valid(raise_exception=True) to do all checks automatically and raise handled errors if it's needed

2023-09-18 14:00 UTC, EdAlekseiev requested changes

2023-09-18 14:00 UTC, EdAlekseiev commented on cinema/views.py
> +            return Response(serializer.data, status=status.HTTP_200_OK)
```suggestion
        serializer.is_valid(raise_exception=True):
        serializer.save()
        return Response(serializer.data, status=status.HTTP_200_OK)

```

2023-09-18 15:08 UTC, VladyslavKlevanskyi commented on cinema/views.py
> +            return Response(serializer.data, status=status.HTTP_200_OK)
Thank you, Eduard!

2023-09-18 18:12 UTC, EdAlekseiev approved these changes
Good job

2025-01-16 03:45 UTC, closed without merging