Develop
mate-academy/py-movie-api pull request #566
Opened 2024-05-20 23:47 UTC by ArtemLeo

2024-05-21 05:52 UTC, vsmutok requested changes

2024-05-21 05:52 UTC, vsmutok commented on cinema/views.py
> +            serializer.save()
Use `serializer.is_valid(raise_exception=True)` to simplify code. When you use raise_exception=True, if the serializer is invalid, an exception (serializers.ValidationError) is raised. DRF catches this exception and automatically returns a 400 Bad Request response with the appropriate error messages.

2024-05-21 05:52 UTC, vsmutok commented on cinema/views.py
> +            serializer.save()
the same

2024-05-21 05:52 UTC, vsmutok commented on cinema/views.py
> +def movie_list(request):
Missed annotations

2024-05-21 11:46 UTC, pavlopro requested changes

2024-05-21 11:46 UTC, pavlopro commented on cinema/views.py
> +        try:
Remove `try-except` as you already added 'raise_exception=True' which will handle it

2024-05-21 11:46 UTC, pavlopro commented on cinema/views.py
> +        try:
Same here

2024-05-24 13:04 UTC, Polyakiv-Andrey approved these changes
Good job!

2026-03-11 02:58 UTC, closed without merging