Solution
mate-academy/py-movie-api pull request #713
Opened 2024-09-27 06:38 UTC by Poznanskyi

2024-09-30 08:32 UTC, Ivan-Shakhman approved these changes

2024-10-03 13:27 UTC, MNDonut requested changes

2024-10-03 13:27 UTC, MNDonut commented on .gitignore
> +#.idea/
seems like you pushed .idea folder to the repository

2024-10-03 13:27 UTC, MNDonut commented on app/urls.py
> +path("api/cinema/", include("cinema.urls", namespace="cinema")),
fix identation

2024-10-03 13:27 UTC, MNDonut commented on cinema/models.py
> +class Movie(models.Model):
2 blank lines after the last import

2024-10-03 13:27 UTC, MNDonut commented on cinema/serializers.py
> +                setattr(instance, field, validated_data[field])
why not instance.title = validated_data[..]?
If some field failed validation, does it mean it'll call this method to update data anyway?

2024-10-05 09:58 UTC, Arsen-hrynevych approved these changes
Overall ok

2025-09-18 13:13 UTC, closed without merging