'Solution'
mate-academy/py-movie-api pull request #716
Opened 2024-09-27 16:08 UTC by TsvetanKichuk

2024-09-27 17:34 UTC, pavlopro requested changes
Remove pycache from PR

2024-09-27 17:34 UTC, pavlopro commented on cinema/views.py
> +        if serializer.is_valid():
`serializer.is_valid(raise_exception=True)`

2024-09-27 17:34 UTC, pavlopro commented on cinema/views.py
> +    else:
Please explicitly check for "DELETE"

2024-09-27 17:34 UTC, pavlopro commented on requirements.txt
> +
remove blank line

2024-09-27 17:34 UTC, pavlopro commented on .gitignore
> +venv/
add blank line

2024-09-27 19:01 UTC, pavlopro requested changes
remove pycache from PR

2024-09-27 19:01 UTC, pavlopro commented on cinema/views.py
> +        if serializer.is_valid(raise_exception=True):
No need to have this `if` operator

2024-09-27 19:01 UTC, pavlopro commented on requirements.txt
> +djangorestframework~=3.15.2
add blank line

2024-09-28 12:30 UTC, pavlopro requested changes
Remove pycache from PR

2024-09-28 12:50 UTC, TsvetanKichuk commented
Hi, I can't remove it

2024-09-28 16:43 UTC, vsmutok requested changes

2024-09-28 16:43 UTC, vsmutok commented on cinema/migrations/__pycache__/0001_initial.cpython-312.pyc
Please remove  `__pycache__` from PR

2024-09-29 11:12 UTC, pavlopro requested changes
remove pycache from PR

2024-09-29 11:37 UTC, closed without merging